name: TNTRun
version: 1.1
api
- 1.0.0
- 2.0.0
main: game\tntrun\TNTRun
author: DavidJBrockway aka MCPE_PluginDev
description: TntRun Minigame TNT_Run Experimental build 
commands:
 tntrun:
  description: "Start TntRun Minigame TNT Run Experimental Build"
  permission: tntrun.plugin.tntrun
permissions:
 tntrun.plugin.tntrun:
  description: "tntrun.plugin.tntrun"
  default: op
