# -------------------------------
# TNTRUN CONFIGURATIONS
# version v1.2
# -------------------------------
# Multi-languages support
# EN - English 
# KO - Korean 
# CN - Chinese
# JP - Japanese
# SP - Spanish
# FR - French
# RU - Russina
# BP - Brazil Portuguese
# .... more
# ---------------------------
#  comming soon language: "EN"
#  comming soon run_selftest_message: "YES"
# -----------------------------
enable_spaw_lobby: "no"
#----------------------------
#----------------------------- 
# play round reset timer in ticks
#-----------------------------
reset_scheduler: "on"
reset_timeout: "8000"
reset_type: "FLOOR"
#---------------------------
# TnTRun lobby location
# ---------------------------
tntrun_lobby_world: "world"
tntrun_lobby_x: "100"
tntrun_lobby_y: "5"
tntrun_lobby_z: "109"
#---------------------------
# TnTRun Arena location
#--------------------------- 
tntrun_arena_world: "world"
tntrun_arena_name: "TNT Run Arena"
tntrun_arena_size: "26"
tntrun_arena_floor: "3"
#---------------------------
tntrun_arena_x: "82"
tntrun_arena_y: "4"
tntrun_arena_z: "118"
#---------------------------
# player entrance
tntrun_arena_enter_x: "86"
tntrun_arena_enter_y: "52"
tntrun_arena_enter_z: "131"
#---------------------------
# TnTRun button JOIN
#--------------------------- 
tntrun_join_button_x: "143"
tntrun_join_button_y: "7"
tntrun_join_button_z: "155"
#---------------------------
# TnTRun button START
#--------------------------- 
tntrun_start_button_x: "89"
tntrun_start_button_y: "54"
tntrun_start_button_z: "130"
#
#---------------------------
# TnTRun button RESET
#--------------------------- 
tntrun_reset_button_x: "142"
tntrun_reset_button_y: "7"
tntrun_reset_button_z: "155"
#--------------------------- 
tntrun_top_exit_button_x: "87"
tntrun_top_exit_button_y: "64"
tntrun_top_exit_button_z: "130"
#---------------------------
# TnTRun top floor Exit button
#--------------------------- 
tntrun_top_exit_button_x: "87"
tntrun_top_exit_button_y: "54"
tntrun_top_exit_button_z: "130"
#
#---------------------------
# TnTRun ground floor Exit button
#--------------------------- 
tntrun_ground_exit_button_x: "93"
tntrun_ground_exit_button_y: "7"
tntrun_ground_exit_button_z: "130"
#---------------------------
# TnTRun Sign JOIN
#--------------------------- 
tntrun_join_sign_x: "99"
tntrun_join_sign_y: "6"
tntrun_join_sign_z: "107"
#---------------------------
# TnTRun Sign START
#--------------------------- 
tntrun_start_sign_x: "144"
tntrun_start_sign_y: "7"
tntrun_start_sign_z: "155"
#
#---------------------------
# TnTRun Sign RESET
#--------------------------- 
tntrun_reset_sign_x: "100"
tntrun_reset_sign_y: "6"
tntrun_reset_sign_z: "107"
#
#---------------------------
# TnTRun Sign STATUS
#--------------------------- 
tntrun_status_sign_x: "101"
tntrun_status_sign_y: "6"
tntrun_status_sign_z: "107"
